typography_spectrum: 0.55103
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0
  lightness: 0.9678325736895204
  saturation: 0.1875
  rhythmicContrast: 0.5
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0
analytics:
  google: null
  facebook: null
  twitter: null
name: Eric Kerkhoven | Portfolio
cta:
  domain: null
  bucket: null
  version: null
navigation:
  - name: CINEMATOGRAPHY
    id: 27e44d7a-6a7c-4c43-8b38-d51518ca8471
    type: content
  - name: DIRECTING
    id: 182dc1bf-bf5f-4b0b-bbef-74449af52cef
    type: content
favicon: null
title: Eric Kerkhoven | Portfolio
purpose: []
