name: 'Eric Kerkhoven | Portfolio'
favicon: null
layout_spectrum: 0.63249656627886
typography_spectrum: 0.9411637294106185
title: 'Eric Kerkhoven | Portfolio'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0
  lightness: 0.9678325736895204
  saturation: 0.1875
  rhythmicContrast: 0.5
purpose: []
